name: Deploy K8s-IA Website to VPS

on:
  push:
    branches:
      - main # ou master, selon votre branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupère le code de votre dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configure Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Connexion au GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Construit l'image Docker et la pousse sur GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Le nom de l'image est adapté à votre projet.
          tags: ghcr.io/${{ github.repository_owner }}/k8s-ia-website:latest

      # 5. Déploiement sur le VPS via SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Se connecter à GHCR sur le serveur
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            # Pull la nouvelle image
            docker pull ghcr.io/${{ github.repository_owner }}/k8s-ia-website:latest
            
            # Arrêter et supprimer l'ancien conteneur s'il existe
            docker stop k8s-ia-container || true
            docker rm k8s-ia-container || true
            
            # Lancer le nouveau conteneur
            docker run -d \
              --restart always \
              -p 3000:3000 \
              --name k8s-ia-container \
              ghcr.io/${{ github.repository_owner }}/k8s-ia-website:latest
            
            # Nettoyer les anciennes images non utilisées pour libérer de l'espace
            docker image prune -f